### ISSUE TITLE
Invalid page token on get_playlist_items

### ISSUE THREAD

**Issue by Urkchar** [sns-sdks/python-youtube#102]
This issue is still happening for me. I got the error message on 2021-08-18 14:20:41,112. 
```
Traceback (most recent call last):
  File "c:\Users\urkch\AppData\Local\Programs\Python\Python_Projects\YouTube Channels Bot\main.py", line 480, in call_api_until_success
    resp = callable(**kwargs)
  File "c:\Users\urkch\AppData\Local\Programs\Python\Python_Projects\YouTube Channels Bot\main.py", line 89, in get_playlist_items
    res_data = self.paged_by_page_token(
  File "c:\Users\urkch\AppData\Local\Programs\Python\Python_Projects\YouTube Channels Bot\main.py", line 136, in paged_by_page_token
    data = self._parse_response(resp)  # origin response
  File "c:\Users\urkch\AppData\Local\Programs\Python\Python_Projects\YouTube Channels Bot\main.py", line 182, in _parse_response
    raise PyYouTubeExceptionDebug(response)
PyYouTubeExceptionDebug: YouTubeException(status_code=400,message=The request specifies an invalid page token.)
```
For what it's worth, this happened on a playlist with lots of videos as mentioned by @z1lc . 
I am using python-youtube version 0.8.1
If you need more information from me, please let me know.

_Originally posted by @Urkchar in https://github.com/sns-sdks/python-youtube/issues/100#issuecomment-901964963_

**Comment by MerleLiuKun** [comment]
Hey, 

That's error from youtube services. We can not solve it,
